test: evaluate skipped tests, fix failing tests, add step in e2e workflow to mark build as failed (#351)
* update test_linode.py

* evaluate skipped tests, add steps in e2e workflow, fix flaky tests

* lint

* fix flaky tests in lke and volume

* add some safety wait until functions for reorder test

* update test_delete_interface_containing_vpc, test_linode_initate_migration

diff --git a/.github/workflows/e2e-test-pr.yml b/.github/workflows/e2e-test-pr.yml
--- a/.github/workflows/e2e-test-pr.yml
+++ b/.github/workflows/e2e-test-pr.yml
@@ -19,6 +19,8 @@ jobs:
     runs-on: ubuntu-latest
     if:
       github.event_name == 'workflow_dispatch' && inputs.sha != ''
+    env:
+      EXIT_STATUS: 0
 
     steps:
       - uses: actions-ecosystem/action-regex-match@v2
@@ -83,8 +85,8 @@ jobs:
           timestamp=$(date +'%Y%m%d%H%M')
           report_filename="${timestamp}_sdk_test_report.xml"
           status=0
-          if ! python3 -m pytest test/integration/${INTEGRATION_TEST_PATH} --junitxml="${report_filename}"; then
-            echo "Tests failed, but attempting to upload results anyway"
+          if ! python3 -m pytest test/integration/${INTEGRATION_TEST_PATH} --disable-warnings --junitxml="${report_filename}"; then
+            echo "EXIT_STATUS=1" >> $GITHUB_ENV
           fi
         env:
           LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
@@ -136,3 +138,12 @@ jobs:
               conclusion: process.env.conclusion
             });
             return result;
+
+      - name: Test Execution Status Handler
+        run: |
+          if [[ "$EXIT_STATUS" != 0 ]]; then
+            echo "Test execution contains failure(s)"
+            exit $EXIT_STATUS 
+          else
+            echo "Tests passed!"
+          fi
