write file upload script using boto3 and change workflow files

diff --git a/.github/workflows/e2e-test-pr.yml b/.github/workflows/e2e-test-pr.yml
--- a/.github/workflows/e2e-test-pr.yml
+++ b/.github/workflows/e2e-test-pr.yml
@@ -78,10 +78,22 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - run: make INTEGRATION_TEST_PATH="${{ inputs.test_path }}" testint
+      - run: |
+          timestamp=$(date +'%Y%m%d%H%M')
+          report_filename="${timestamp}_sdk_test_report.xml"
+
+          if python3 -m pytest test/integration/${INTEGRATION_TEST_PATH} --junitxml="${report_filename}"; then
+            python3 test/script/test_report_upload_script.py "${report_filename}"
+          else
+            echo "Tests failed, but attempting to upload results anyway"
+            python3 test/script/test_report_upload_script.py "${report_filename}"
+            exit 1
+          fi
         if: ${{ steps.validate-tests.outputs.match == '' }}
         env:
           LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
+          LINODE_CLI_OBJ_ACCESS_KEY: ${{ secrets.LINODE_CLI_OBJ_ACCESS_KEY }}
+          LINODE_CLI_OBJ_SECRET_KEY: ${{ secrets.LINODE_CLI_OBJ_SECRET_KEY }}
 
       - uses: actions/github-script@v6
         id: update-check-run
